### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sandorvasas** [duffman/tspath#13]
This appears when I run `tspath -f` (or `tspath`):
```
/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2446
        type = expr.type || Syntax.Property;
                    ^

TypeError: Cannot read property 'type' of undefined
    at CodeGenerator.generateExpression (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2446:21)
    at CodeGenerator.CallExpression (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:1870:34)
    at CodeGenerator.generateExpression (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2452:28)
    at CodeGenerator.VariableDeclarator (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:1436:26)
    at CodeGenerator.generateStatement (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2465:33)
    at block (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:1459:38)
    at CodeGenerator.VariableDeclaration (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:1477:17)
    at CodeGenerator.generateStatement (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2465:33)
    at CodeGenerator.Program (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:1707:43)
    at CodeGenerator.generateStatement (/home/sandor/.nvm/versions/node/v8.10.0/lib/node_modules/tspath/node_modules/escodegen/escodegen.js:2465:33)
```

**Comment by duffman** [comment]
You need at least Node 9.x in order to run tspath
