### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 381

### ISSUE THREAD

**Issue by jplew** [duffman/tspath#21]
Hi, I'm getting this error:

```
$  npx tspath
TSPath 1.3.7
? Process project at: </Users/jplew/Sites/mysite/ops/apps/api/> ? true
undefined:20
}
^

SyntaxError: Unexpected token } in JSON at position 381
    at JSON.parse (<anonymous>)
    at ParserEngine.readConfig (/Users/jplew/Sites/mysite/ops/apps/api/node_modules/tspath/src/parser-engine.js:213:30)
    at ParserEngine.execute (/Users/jplew/Sites/mysite/ops/apps/api/node_modules/tspath/src/parser-engine.js:90:36)
    at TSPath.processPath (/Users/jplew/Sites/mysite/ops/apps/api/node_modules/tspath/src/tspath.js:39:25)
    at Confirm.callback (/Users/jplew/Sites/mysite/ops/apps/api/node_modules/tspath/src/tspath.js:29:27)
    at Confirm.<anonymous> (/Users/jplew/Sites/mysite/ops/apps/api/node_modules/prompt-base/index.js:625:10)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

My tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "rootDir": "src",
    "outDir": "dist",
    "lib": [
      "esnext", "dom"
    ],
    "baseUrl": "./src",
    "paths": {
      "@root/*": ["./*"],
      "@resolvers/*": ["resolvers/*"]
    }
  },
  "include": ["src"],
  "exclude": ["src/generated"],
}
```
My project structure: 
![image](https://user-images.githubusercontent.com/462836/48647643-69de8f80-e9a1-11e8-9347-f1d6bd6bc16d.png)

I also added this to my package.json:
```
  "_moduleAliases": {
    "@root": "./dist",
    "@resolvers": "./dist/resolvers"
  }
```

Node version: 8.11.2

Any ideas?

**Comment by duffman** [comment]
First of all, your tsconfig contains an error:

{
  "compilerOptions": {
    "target": "es5",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "rootDir": "src",
    "outDir": "dist",
    "lib": [
      "esnext", "dom"
    ],
    "baseUrl": "./src",
    "paths": {
      "@root/*": ["./*"],
      "@resolvers/*": ["resolvers/*"]
    }
  },
  "include": ["src"],
  "exclude": ["src/generated"], <---
}


I also added this to my package.json:

"_moduleAliases" is nothing TSPath will recognize (read at all)


  "_moduleAliases": {
    "@root": "./dist",
    "@resolvers": "./dist/resolvers"
  }

If it would turn out to be a JS file it cannot parse  would it be possible
for you to email me the file it file it fails to parse?
if yes, please drop it at patfor@gmail.com and I´ll have a look :)

I´m having trouble seeing everything on my damn small iPhone 5, it might
even be I haven´t "interpeted" everything correctly =)
//Duffman
