### ISSUE TITLE
Not reading output file directly

### ISSUE THREAD

**Issue by ntucker** [duffman/tspath#29]
```
tucker@GLaDOS:/mnt/e/Webdesign/salted-vagrant/rest-hooks$ npx tspath
TSPath 1.3.7
? Process project at: </mnt/e/Webdesign/salted-vagrant/rest-hooks/> ? true
Parsing project: rest-hooks /mnt/e/Webdesign/salted-vagrant/rest-hooks/
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/mnt/e/Webdesign/salted-vagrant/rest-hooks/src/lib'
    at Object.readdirSync (fs.js:806:3)
    at ParserEngine.walkSync (/mnt/e/Webdesign/salted-vagrant/rest-hooks/node_modules/tspath/src/parser-engine.js:260:24)
    at ParserEngine.execute (/mnt/e/Webdesign/salted-vagrant/rest-hooks/node_modules/tspath/src/parser-engine.js:101:14)
    at TSPath.processPath (/mnt/e/Webdesign/salted-vagrant/rest-hooks/node_modules/tspath/src/tspath.js:39:25)
    at Confirm.callback (/mnt/e/Webdesign/salted-vagrant/rest-hooks/node_modules/tspath/src/tspath.js:29:27)
    at Confirm.<anonymous> (/mnt/e/Webdesign/salted-vagrant/rest-hooks/node_modules/prompt-base/index.js:625:10)
    at processImmediate (timers.js:637:19)
```

Usually I build via `tsc --emitDeclarationOnly -p ./src`. This outputs ambient declarations to the lib folder. But for some reason tspath is try to go to src/lib instead.

tsconfig.json
```json
{
  "compilerOptions": {
    /* Basic Options */
    "target": "esnext",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "react",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "declaration": true,                      /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "lib",                         /* Redirect output structure to the directory. */
    "rootDir": "./src",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./src",                       /* Base directory to resolve non-absolute module names. */
    "paths": {"~/*": ["*"]},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": ["./src"],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    "allowSyntheticDefaultImports": true,     /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true         /* Enables experimental support for emitting type metadata for decorators. */
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by alanhchoi** [comment]
It is the same issue with https://github.com/duffman/tspath/issues/2.

@duffman wrote that it has been fixed v1.3.5. But the command-line script in the published package is still working wrong, because the script file in `bin` field of `package.json` still contains wrong code.

```javascript
// package.json L:7

  "bin": {
    "tspath": "src/tspath.js"
  },
```

```javascript
// src/parser-engine.js L:98

        this.appRoot = path.resolve(this.projectPath, this.projectOptions.baseUrl);
        this.appRoot = path.resolve(this.appRoot, this.projectOptions.outDir);
```
