### ISSUE TITLE
Error when used in CI/CD

### ISSUE THREAD

**Issue by cerbaire** [duffman/tspath#53]
When running tspath in a CI/CD script, I have the following error:

> npx tspath -f -s
TSPath v2.6.8
Try: 'tspath --help' for more information
Parsing project: my-project /opt/gitlab-runner/builds/xxx/yyy/packages/my-project/
Indexing files...
/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/utils/utils.js:64
        process.stdout.clearLine();
                       ^
TypeError: process.stdout.clearLine is not a function
    at Function.updateLine (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/utils/utils.js:64:24)
    at ParserEngine.walkSync (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:438:31)
    at ParserEngine.walkSync (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:435:33)
    at ParserEngine.walkSync (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:435:33)
    at ParserEngine.<anonymous> (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:148:18)
    at Generator.next (<anonymous>)
    at /opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:27:12)
    at ParserEngine.execute (/opt/gitlab-runner/builds/xxx/yyy/node_modules/tspath/parser-engine.js:112:16)

I can reproduce the same error local using the following command:
npx tspath -f -s > debug.log

I don't see any difference on console output when using -s parameter.

Any idea? 

Thanks for your support

**Comment by The-White-Fang** [comment]
Did you manage to fix it? I am encountering the same error.

**Comment by The-White-Fang** [comment]
For anyone who is looking for a solution to this.
Use `patch-package` to patch tspath

Step 1: Install `patch-package` by `npm i patch-package`
Step 2: Make changes to `node_modules/tspath/utils/utils.js` and `node_modules/tspath/parser-engine.js`
Step 3: Run `npx patch-package tspath`
Step 4: Commit the changes.
Step 5: Add a docker step after `npm i`, `npx patch-package`.
Step 6: Purge build cache `docker system prune -a` and rebuild the image.

**Comment by cerbaire** [comment]
Yes. I used resolve-tspaths instead of tspath.

Le mer. 1 nov. 2023 à 06:56, Abhishek Singh ***@***.***> a
écrit :
